### ISSUE TITLE
Dependency installation fails on Windows

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-policy#171]
A user on Windows has to manually `npm i` for policy pack downloads as automatic installation fails each time.

![image](https://user-images.githubusercontent.com/293763/70812867-4ab95980-1d7d-11ea-804d-09995fdf3dd8.png)

**Comment by mariusfeteanu** [comment]
That's my windows version
![windows-version](https://user-images.githubusercontent.com/9166284/70813657-c0471900-1dc1-11ea-8610-3e8485006b07.png)

This happens the first time Pulumi tries to download the policy pack. After `npm install` the policy is succesfully checked.

I have not checked if new versions of a policy require `npm install` as well.

**Comment by justinvp** [comment]
Another user report of this: https://github.com/pulumi/pulumi-policy/issues/56#issuecomment-578958024

> I keep getting errors when running pulumi preview||up when there is no pack installed yet. Pulumi does not recognize if it has successfully installed the policy packs (and it has).

```
error: failed to install dependencies of policy pack; you may need to re-run npm install in "/home/user/.pulumi/policies/pulumi-analyzer-gcp-typescript-v1" before this policy pack works: npm install reported success, but node_modules directory is missing
```

> Im using Fedora 29.
> "npm version" result:
> `{ npm: '6.9.0', ares: '1.15.0', brotli: '1.0.7', cldr: '35.1', http_parser: '2.9.2', icu: '64.2', modules: '64', napi: '4', nghttp2: '1.34.0', node: '10.16.0', openssl: '1.1.1b', tz: '2019a', unicode: '12.1', uv: '1.29.1', v8: '6.8.275.32-node.52', zlib: '1.2.11' }`
> 
> pulumi version : v1.9.0
> 
> But note that this error is happening inside the pulumi/pulumi container as well. (the latest available).

**Comment by justinvp** [comment]
I was able to reproduce this and know what the underlying problem is.

This happens when running `pulumi preview` or `pulumi up` against a non-NodeJS Pulumi stack that has a Policy Pack applied.

The underlying problem is we're not making use of the `dir` parameter that was passed into the `npm.Install` function (where this check is implemented) when checking if the `node_modules` directory exists, which means we end up looking for it in the _current working directory_ rather than in the `dir` directory. In this case, the current working directory is the directory of the Pulumi program, and the `dir` parameter is the directory containing the Policy Pack. If you happened to be using a NodeJS Pulumi program, the check would succeed because the Pulumi program itself has a `node_modules` directory, and it would be incorrectly checking if that directory exists. But if your Pulumi program is written in another language, it wouldn't have a `node_modules` directory and the check fails.

This is the problematic code:

https://github.com/pulumi/pulumi/blob/b6b313821c893e6c5c4727c018de20edb340589f/pkg/npm/npm.go#L77-L80

```go
	// Ensure the "node_modules" directory exists.
	if _, err := os.Stat("node_modules"); os.IsNotExist(err) {
		return bin, errors.Errorf("%s install reported success, but node_modules directory is missing", bin)
	}
```

The fix is to change it to be something like:

```go
	// Ensure the "node_modules" directory exists.
	nodeModulesPath := filepath.Join(dir, "node_modules")
	if _, err := os.Stat(nodeModulesPath); os.IsNotExist(err) {
		return bin, errors.Errorf("%s install reported success, but node_modules directory is missing", bin)
	}
```

@jkisk, want to open a PR in https://github.com/pulumi/pulumi with a fix?

**Comment by justinvp** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/3837

**Comment by pasquinid** [comment]
@justinvp I upgraded to the 1.9.1 but still get this error, is there anything more I should do?

**Comment by justinvp** [comment]
@pasquinid, the fix has been merged in master, but has not been released yet. I believe the plan is to release 1.10 mid next week.
